# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xls_dealwith.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 619, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openFile.setObjectName("openFile")
        self.horizontalLayout.addWidget(self.openFile)
        self.saveFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveFile.setObjectName("saveFile")
        self.horizontalLayout.addWidget(self.saveFile)
        self.translate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.translate.setObjectName("translate")
        self.horizontalLayout.addWidget(self.translate)
        self.toChina = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.toChina.setObjectName("toChina")
        self.horizontalLayout.addWidget(self.toChina)
        self.toEnglish = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.toEnglish.setObjectName("toEnglish")
        self.horizontalLayout.addWidget(self.toEnglish)
        self.toFrench = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.toFrench.setObjectName("toFrench")
        self.horizontalLayout.addWidget(self.toFrench)
        self.toJapan = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.toJapan.setObjectName("toJapan")
        self.horizontalLayout.addWidget(self.toJapan)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 40, 641, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(300)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFile.setText(_translate("MainWindow", "打开文件"))
        self.saveFile.setText(_translate("MainWindow", "保存"))
        self.translate.setText(_translate("MainWindow", "翻译成"))
        self.toChina.setText(_translate("MainWindow", "中文"))
        self.toEnglish.setText(_translate("MainWindow", "英文"))
        self.toFrench.setText(_translate("MainWindow", "法语"))
        self.toJapan.setText(_translate("MainWindow", "日语"))
